### ISSUE TITLE
Please tag releases

### ISSUE THREAD

**Issue by bdrung** [saltstack/pytest-skip-markers#9]
Please tag the releases to allow using `git archive` to generate source tarballs for Debian packaging.

Side note: pytest-skip-markers-1.1.0.tar.gz on https://pypi.org/project/pytest-skip-markers/ seems to be nearly empty.

**Comment by s0undt3ch** [comment]
The releases made have tags on the repo, so I'm not sure what the issue actually is.

**Comment by bdrung** [comment]
Thanks. Is it intentional that the tag `1.1.0` differs by two commits from the current master branch (despite the two commits having the same content)?

**Comment by s0undt3ch** [comment]
Hmm, that difference is indeed non intentional, I'll investigate what happened.
Thanks for the update.

**Comment by s0undt3ch** [comment]
I do remember making some changes on the change log and deleting the tag before pushing it.
Maybe I messed up there

**Comment by s0undt3ch** [comment]
I just made a release. I think we didn't hit this issue again.
Let me know otherwise.

**Comment by bdrung** [comment]
Yes, the following tags are correctly set. You can fix the `1.1.0` by deleting it and pushing the corrected one:
```
git push origin :1.1.0
git push origin 1.1.0
```
